version: 2.1

executors:
  python-chromedriver-executor:
    docker:
      - image: joyzoursky/python-chromedriver:3.9
    working_directory: ~/repo

jobs:
  setup:
    executor: python-chromedriver-executor
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run Behave API Tests
          command: |
            behave --tags=@API -f html -o behave-report.html
      - run:
          name: Run Behave UI Tests
          command: |
            HEADLESS=true behave --tags=@UI -f html -o behave-report.html  

workflows:
  version: 2
  test:
    jobs:
      - setup