version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.9  # Use a Python 3.9 Docker image
    environment:
      SELENIUM: /usr/bin/google-chrome
    working_directory: ~/repo

jobs:
  setup:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Download and install Chrome
          command: |
            sudo wget -O chrome-linux64.zip https://storage.googleapis.com/chrome-for-testing-public/127.0.6533.72/linux64/chrome-linux64.zip
            sudo ls
            unzip chrome-linux64.zip
            sudo rm chrome-linux64.zip
            sudo mv chrome-linux64 /opt/chrome/
            sudo ln -s /opt/chrome/chrome /usr/local/bin/
      - run:
          name: Download and install ChromeDriver
          command: |
            sudo wget -N https://storage.googleapis.com/chrome-for-testing-public/127.0.6533.72/linux64/chromedriver-linux64.zip
            unzip chromedriver-linux64.zip
            sudo rm chromedriver-linux64.zip
            sudo mv chromedriver-linux64 /usr/local/bin/
            chrome --version
            chromedriver --version
      - run:
          name: Run Behave API Tests
          command: |
            behave --tags=@API -f html -o behave-report.html
      - run:
          name: Run Behave UI Tests
          command: |
            behave --tags=@UI -f html -o behave-report.html  

workflows:
  version: 2
  test:
    jobs:
      - setup